### ISSUE TITLE
RDFLib: read remote turtle files (e.g. from web link)

### ISSUE THREAD

**Issue by tian3rd** [anusii/rdflib#16]
E.g., 

```dart
// ...
Graph g = Graph();
g.parse('http://www.w3.org/People/Berners-Lee/card');
// ...
```

**Comment by tian3rd** [comment]
For test purpose, we can try to parse this link: http://www.w3.org/2002/07/owl#

**Comment by zheyxu** [comment]
Made pr https://github.com/anusii/rdflib/pull/45
The webLink should point to a valid Turtle (.ttl) file to ensure correct parsing.
 If the webLink does not point to a .ttl file, it might cause unexpected parsing errors.

**Comment by zheyxu** [comment]
Check with 
```
  String webLink = 'https://www.w3.org/TR/turtle/examples/example3.ttl';

  // Create a graph to read Turtle file and store info.
  Graph g = Graph();

  // Parse the Turtle file from the web.
  await g.parseTurtleFromWeb(webLink);```

**Comment by zheyxu** [comment]
The web link must be end with '.ttl'.
`await g.parseTurtleFromWeb('https://www.w3.org/2002/07/owl#')` does not work in this case.
But if copy and paste content of 'https://www.w3.org/2002/07/owl#' to a local file, and named it example_ttl_6.dart.
The following code works.
`
String filePath = 'example/sample_ttl_6.ttl';
  // Read file content to a local String
  String fileContents = await File(filePath).readAsStringSync();
  g.parseTurtle(fileContents);
`
