### ISSUE TITLE
RDFLIB: Update the solid_auth and rdflib packages to http: 1.1.0

### ISSUE THREAD

**Issue by gjwgit** [anusii/rdflib#24]
```
13 Oct 10:34:05 gjw@yoga ~gurriny/clinic$ flutter pub upgrade --dry-run
Resolving dependencies... (4.3s)
Because clinic depends on rdflib ^0.2.4 which depends on http ^0.13.5, http ^0.13.5 is required.
So, because clinic depends on http ^1.1.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on http: flutter pub add http:^0.13.6
```

**Comment by Zheyuan-Robert-Xu** [comment]
solid_auth 0.1.11 depends on http ^0.13.4 and no versions of solid_auth match >0.1.11 <0.2.0, solid_auth ^0.1.11 requires http ^0.13.4.
So, because clinic depends on both solid_auth ^0.1.11 and http ^1.1.0, version solving failed.

**Comment by gjwgit** [comment]
Thanks @Zheyuan-Robert-Xu. We might just have to stop using dart_code_metrics. Or buy a license for the new one which might be a good idea for us any how.

@anushkavidanage when you have a chance please update solid_auth. Also need to update rdflib and push it out.

**Comment by gjwgit** [comment]
Assign to @anushkavidanage - update http version in soild_auth.

**Comment by anushkavidanage** [comment]
https://pub.dev/packages/solid_auth

**Comment by anushkavidanage** [comment]
Updated
