### ISSUE TITLE
RDF: read full example `ttl` data in anusii/pods with `RDFLib` package

### ISSUE THREAD

**Issue by tian3rd** [anusii/rdflib#3]

**Comment by Zheyuan-Robert-Xu** [comment]
@tian3rd According to the use of the package, I raised some issues:

- [ ] Write _@base <http://sii.cecs.anu.edu.au/onto/SOLID-Health> ._ at the end of the prefix session

**Comment by tian3rd** [comment]
@Zheyuan-Robert-Xu Thanks for raising this issue, I'm discussing it with @Sergio 
For a temporary quick fix, I have updated the `rdflib` to the latest version where I just ignore lines starting with '@base` which should generate the outcome of parsing or serializing without errors.

**Comment by tian3rd** [comment]
See the [change log](https://pub.dev/packages/rdflib/changelog) for detail.

**Comment by tian3rd** [comment]
The full example data I use: https://github.com/anusii/pods/blob/main/datasets/turtle-data/SOLID-Health-Ontology-Example%20-%20(data).ttl

Read this file --> store triples in graph --> serialize graph to a new `ttl` file, we get the file: https://github.com/anusii/rdflib/blob/main/example/ex_full_processed.ttl

**Comment by Zheyuan-Robert-Xu** [comment]
Thanks, Phillip! And is it possible to separate the whole ttl file into patient id-specific files, like p12460.ttl file?

**Comment by tian3rd** [comment]
> Thanks, Phillip! And is it possible to separate the whole ttl file into patient id-specific files, like p12460.ttl file?

It's possible, for example, you can check each triple in your graph, and extract those which meet your id criteria. And then export it to a different `ttl` file.

It much depends on your workflow of organizing patient data in the first place.

**Comment by Zheyuan-Robert-Xu** [comment]
The value of Literal is limited to a String. The value also needs to cover float, int.
Literal(this.value, {this.datatype, this.lang})

**Comment by tian3rd** [comment]
> The value of Literal is limited to a String. The value also needs to cover float, int. Literal(this.value, {this.datatype, this.lang})

Hi @Zheyuan-Robert-Xu, you can check the Literal datatype first, if it's a xsd:float type, then you can convert the value back to a double type in dart.

**Comment by Zheyuan-Robert-Xu** [comment]
But when the record was written in the turtle file, it adds double quotation marks to the value.    
sh-onto:systolicBloodPressure "123"^^xsd:int .

**Comment by tian3rd** [comment]
Exactly, so that when you parse it into your graph, you can check the object (`Literal` in this case) datatype first, which should be URIRef(XSD.int), then you're guranteed that the Literal's value "123" can be converted to an integer.
