### ISSUE TITLE
RDFLib: SPARQL to support navigation in `Graph`

### ISSUE THREAD

**Issue by tian3rd** [anusii/rdflib#38]
Add properties such as:

- [x] `g.value` to find out any triple that has a single `rdf:value`
- [x] `g.subjects` to extract all subjects in the graph
- [x] `g.predicates`
- [x] `g.objects`

**Comment by zheyxu** [comment]
g.subjects, g.predicates and g.objects are updated with optional arguments.

**Comment by zheyxu** [comment]
Made pr https://github.com/anusii/rdflib/pull/40
