### ISSUE TITLE
RDFLib: test writing ttl files with RDFLib

### ISSUE THREAD

**Issue by jesscmoore** [anusii/rdflib#8]

**Comment by tian3rd** [comment]
Currently, `RDFLib` can write turtle file to a local destination (e.g. in local storage in our mobile device, with the help of `path_provider`). 

1. Writing to server can be done by using `http.put` request without authorization if it's allowed. For example, in the root `.acl` folder of `solid.udula.net.au`, anyone can create files or folders. So we can just use a put method to create the corresponding turtle files. E.g.

```bash
curl -X PUT -H "Content-Type: text/turtle" \
                   -d "<a> <b> <c> ." \
                   https://solid.udula.net.au/new_folder/new_turtle.ttl
```

will create a new file `new_turtle.ttl` in the new folder `new_folder` on our udula server.

2. Writing to a private pod (e.g. charlie bruegel's pod), we need to pass in the access token as well as the `dpop` token in the `http.put` request, which can be done in our flutter app like this:

```dart
///
final actionResponse = await http.put(
    Uri.parse(destUrl), // 
    headers: {
      'Accept': '*/*',
      'Authorization': 'DPoP $accessToken', // accessToken is from authData map
      'Connection': 'keep-alive',
      'Content-Type': 'text/turtle', // this also applies to .acl files
      'Content-Length': testTriple.length.toString(),
      'DPoP': dPopToken, // dPopToken is generated with`genDpopToken(destUrl, rsaKeyPair, publicKeyJwk, 'PUT')`
    },
    body: tripleContents, // the long string that has all the content for the turtle file
  );
```

**Comment by tian3rd** [comment]
I'm also thinking that if these `http` requests are universal for the CRUD operations to interact with Community Solid Servers, maybe it's good to integrate it into the `RDFLib` package as a module. 

For example, the operations we're using include http patch requests with `SPARQL` queries for updating the turtle files, http put for creating new turtle files, http get for fetching data, etc.
