### ISSUE TITLE
RDFLib: fix ':' and '@base' in namespace prefixes

### ISSUE THREAD

**Issue by tian3rd** [anusii/rdflib#9]
When the turtle file contains `:` or `@base` in the namespace prefixes, they'll be ignored in current RDFLib implementation. Need to save them in the graph, and parse and serialize correctly in the `Graph` class.

**Comment by tian3rd** [comment]
Updated change-log for `RDFLib` package:

- `graph.dart`: add support for parsing and writing @base and @prefix : in namespace prefixes section
- `constants.dart`: create constants in this file to be imported to other files if necessary

**Comment by tian3rd** [comment]
Example file 1: https://github.com/anusii/rdflib/blob/main/example/ex_base.ttl as an input
Example file 2: https://github.com/anusii/rdflib/blob/main/example/ex_base_output.ttl as the output file

Read Example file 1 into the Graph, and serialize the Graph to a turtle file Example file 2.

**Comment by gjwgit** [comment]
Looks good - so RDFLib can now does this - read's file 1 and writes file 2. If that is the case we can close this issue now.
